 exports.FoodCategories = [
  // //drinks
    {
      name: "sprite 2l ",
      price: 25,
      description: "",
      category: "soft drink",
      image: "food/drink (1).jpg",
    },
    {
      name: "coca cola ",
      price: 25,
      description: "",
      category: "soft drink",
      image: "food/drink (1).png",
    },
    {
      name: "coca cola",
      price: 10,
      description: "",
      category: "soft drink",
      image: "food/drink (2).png",
    },
    {
      name: "pepsi 2L",
      price: 26,
      description: "",
      category: "soft drink",
      image: "food/drink (3).jpg",
    },
    {
      name: "coca cola 2L",
      price: 30,
      description: "",
      category: "soft drink",
      image: "food/drink (3).png",
    },
    {
      name: "sprite",
      price: 9,
      description: "",
      category: "soft drink",
      image: "food/drink (4).jpg",
    },
    {
      name: "coca cola",
      price: 19,
      description: "",
      category: "soft drink",
      image: "food/drink (4).png",
    },
    {
      name: "coca cola",
      price: 12,
      description: "",
      category: "soft drink",
      image: "food/drink (5).png",
    },
    {
      name: "orange juice",
      price: 14,
      description: "",
      category: "soft drink",
      image: "food/drink (6).png",
    },
    {
      name: "blue juice",
      price: 14,
      description: "",
      category: "soft drink",
      image: "food/drink (7).png",
    },
  

  //burgers
 
    {
      name: "Chicken burger",
      price: 50,
      description: "",
      category: "burger",
      image: "food/burger (1).png",
    },
    {
      name: "Beef burger && chips",
      price: 40,
      description: "",
      category: "burger",
      image: "food/burger (2).png",
    },
    {
      name: "Ham burger",
      price: 45,
      description: "",
      category: "burger",
      image: "food/burger (3).png",
    },
    {
      name: "American burger",
      price: 49,
      description: "",
      category: "burger",
      image: "food/burger (4).png",
    },
    {
      name: "The Big burger",
      price: 60,
      description: "",
      category: "burger",
      image: "food/burger (5).png",
    },
    {
      name: "double stack burger",
      price: 70,
      description: "",
      category: "burger",
      image: "food/burger (6).png",
    },
    {
      name: "Chicken burger && chips && a drink",
      price: 56,
      description: "",
      category: "burger",
      image: "food/burger (7).png",
    },
    {
      name: "Neapolitan Pizza",
      price: 70,
      description: "",
      category: "burger",
      image: "food/pizza (1).png",
    },
    {
      name: "Chicago Pizza",
      price: 75,
      description: "",
      category: "pizza",
      image: "food/pizza (2).png",
    },
    {
      name: "New York-Style Pizza",
      price: 105,
      description: "",
      category: "pizza",
      image: "food/pizza (3).png",
    },
    {
      name: "American pizza",
      price: 99,
      description: "",
      category: "pizza",
      image: "food/pizza (4).png",
    },
    {
      name: "The Big pizza",
      price: 85,
      description: "",
      category: "pizza",
      image: "food/pizza (5).png",
    },
    {
      name: " Sicilian Pizza",
      price: 90,
      description: "",
      category: "pizza",
      image: "food/pizza (6).png",
    },

    {
      name: "red wine",
      price: 180,
      description: "",
      category: "wine",
      image: "food/wine (6).png",
    },
    {
      name: "corona extra",
      price: 200,
      description: "",
      category: "wine",
      image: "food/wine (5).png",
    },
    {
      name: "korbel",
      price: 250,
      description: "",
      category: "wine",
      image: "food/wine (4).png",
    },
    {
      name: "Willian Valley",
      price: 350,
      description: "",
      category: "wine",
      image: "food/wine (3).png",
    },
    {
      name: "Feriearia green",
      price: 310,
      description: "",
      category: "wine",
      image: "food/wine (2).png",
    },
    {
      name: "sordons wine",
      price: 270,
      description: "",
      category: "wine",
      image: "food/wine (1).png",
    },
  
    {
      name: "chicken Salad Supreme",
      price: 120,
      description: "",
      category: "salad",
      image: "food/salad (4).png",
    },
    {
      name: "Leafy Green Salad",
      price: 110,
      description: "",
      category: "salad",
      image: "food/salad (3).png",
    },
    {
      name: "Greek Salad",
      price: 80,
      description: "",
      category: "salad",
      image: "food/salad (3).jpg",
    },
    {
      name: "Arabic Fattoushe",
      price: 85,
      description: "",
      category: "salad",
      image: "food/salad (2).jpg",
    },
    {
      name: "Insalata Caprese II",
      price: 99,
      description: "",
      category: "salad",
      image: "food/salad (2).png",
    },
    {
      name: "Waldorf  Salad Supreme",
      price: 94,
      description: "",
      category: "salad",
      image: "food/salad (1).png",
    },
    {
      name: "Ambrosia Salad Supreme",
      price: 93,
      description: "",
      category: "salad",
      image: "food/salad (1).jpg",
    },
  
];
